# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chat.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04grpc\"8\n\x07Message\x12\x10\n\x08username\x18\x01 \x01(\t\x12\n\n\x02to\x18\x02 \x01(\t\x12\x0f\n\x07message\x18\x03 \x01(\t\"\x16\n\x02Id\x12\x10\n\x08username\x18\x01 \x01(\t\"2\n\x0cListAccounts\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08wildcard\x18\x02 \x01(\t\"!\n\rCreateAccount\x12\x10\n\x08username\x18\x01 \x01(\t\"#\n\x0fReceiveMessages\x12\x10\n\x08username\x18\x01 \x01(\t\"!\n\rDeleteAccount\x12\x10\n\x08username\x18\x01 \x01(\t\"\x19\n\x05\x43lose\x12\x10\n\x08username\x18\x01 \x01(\t\"\'\n\x05Reply\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\x32\xe5\x02\n\nChatServer\x12)\n\x0bSendMessage\x12\r.grpc.Message\x1a\x0b.grpc.Reply\x12\'\n\nChatStream\x12\x08.grpc.Id\x1a\r.grpc.Message0\x01\x12\x33\n\x10SendListAccounts\x12\x12.grpc.ListAccounts\x1a\x0b.grpc.Reply\x12\x35\n\x11SendCreateAccount\x12\x13.grpc.CreateAccount\x1a\x0b.grpc.Reply\x12\x39\n\x13SendReceiveMessages\x12\x15.grpc.ReceiveMessages\x1a\x0b.grpc.Reply\x12\x35\n\x11SendDeleteAccount\x12\x13.grpc.DeleteAccount\x1a\x0b.grpc.Reply\x12%\n\tSendClose\x12\x0b.grpc.Close\x1a\x0b.grpc.Replyb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MESSAGE._serialized_start=20
  _MESSAGE._serialized_end=76
  _ID._serialized_start=78
  _ID._serialized_end=100
  _LISTACCOUNTS._serialized_start=102
  _LISTACCOUNTS._serialized_end=152
  _CREATEACCOUNT._serialized_start=154
  _CREATEACCOUNT._serialized_end=187
  _RECEIVEMESSAGES._serialized_start=189
  _RECEIVEMESSAGES._serialized_end=224
  _DELETEACCOUNT._serialized_start=226
  _DELETEACCOUNT._serialized_end=259
  _CLOSE._serialized_start=261
  _CLOSE._serialized_end=286
  _REPLY._serialized_start=288
  _REPLY._serialized_end=327
  _CHATSERVER._serialized_start=330
  _CHATSERVER._serialized_end=687
# @@protoc_insertion_point(module_scope)
